version: '3.9'

services:
  wallet-db:
    image: postgres:15
    container_name: wallet_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d wallet_db"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - wallet-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      wallet-db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/data/pgadmin
    networks:
      - wallet-network

  wallet-service:
    build: .
    container_name: wallet_service
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      wallet-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://wallet-db:5432/wallet_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      SPRING_R2DBC_URL: r2dbc:postgresql://wallet-db:5432/wallet_db
      SPRING_R2DBC_USERNAME: admin
      SPRING_R2DBC_PASSWORD: admin

      SPRING_LIQUIBASE_ENABLED: "true"

      JAVA_OPTS: "-Xms256m -Xmx512m"
    networks:
      - wallet-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  wallet-network:
    driver: bridge
